author: Remato
name: Trello Card & GitHub PR Integration
description: Integrate GitHub pull requests with Trello cards
branding:
    color: gray-dark
    icon: link
inputs:
    github-token:
        description: Github token, https://docs.github.com/en/actions/reference/authentication-in-a-workflow.
        required: true
    github-require-keyword-prefix:
        description: When set to true, match only URLs prefixed with “Closes” etc. Just like https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.
        default: false
    github-enable-related-keyword-prefix:
        description: When set to true, ignore URLs prefixed with "Related".
        default: false
    github-require-trello-card:
        description: Throw an error if no Trello cards can be found in the PR description.
        default: false
    github-include-pr-comments:
        description: Include PR comments when searching for Trello cards.
        default: true
    github-include-pr-commit-messages:
        description: Include PR commit messages when searching for Trello cards. If card ID is found, it automatically comments card URL to the PR.
        default: false
    github-include-pr-branch-name:
        description: Include PR branch name when searching for Trello cards (e.g. "1234-card-title"). If card ID is found, it automatically comments card URL to the PR.
        default: false
    github-allow-multiple-cards-in-pr-branch-name:
        description: Allows to reference multiple card short IDs in the branch name (e.g. feature/38-39-40-foo-bar). Option github-include-pr-branch-name needs to be true.
        default: false
    github-include-new-card-command:
        description: Creates a new Trello card from PR details if "/new-trello-card" is written in the PR description. Replaces "/new-trello-card" with the card link.
        default: false
    github-users-to-trello-users:
        description: |-
            Newline-separated list of mapping between Github username and Trello username. Example:
            github-users-to-trello-users: |-
              GithubUser1:TrelloUser1
              GithubUser2:TrelloUser2
    github-add-labels-to-pr:
        description: Adds first mentioned Trello card labels to the PR. Labels must have same names in Trello and GitHub repository.
        default: false
    github-conflicting-labels:
        description: |-
            List of label names separated by semicolon that should not coexist together (e.g. "feature;bug;chore"). If PR has one and the card has another one, then the card label is ignored.
            Example:
            github-conflicting-labels: |-
              feature;bug;chore
              foo;bar
    github-labels-to-trello-labels:
        description: |-
            Newline-separated list of mapping between Github labels and Trello labels. Example:
            github-labels-to-trello-labels: |-
              bugfix:bug
              foo:bar
    trello-api-key:
        description: Trello API key, visit https://trello.com/app-key for key.
        required: true
    trello-auth-token:
        description: Trello auth token, visit https://trello.com/app-key then click generate a token.
        required: true
    trello-organization-name:
        description: Your organization name to avoid assigning cards to outside members. Edit your workspace details and look for the short name.
    trello-board-id:
        description: Trello board ID where to move the cards.
    trello-list-id-pr-draft:
        description: Trello list ID for draft pull request.
    trello-list-id-pr-open:
        description: Trello list ID for open pull request.
    trello-list-id-pr-changes-requested:
        description: Trello list ID for a pull request which has at least one review requesting for changes.
    trello-list-id-pr-approved:
        description: Trello list ID for a pull request which has at least one approve and no reviews requesting for changes.
    trello-list-id-pr-closed:
        description: Trello list ID for closed pull request.
    trello-add-labels-to-cards:
        description: Enables the automatic addition of labels to cards.
        default: true
    trello-add-pr-labels:
        description: Adds GitHub PR labels to cards.
        default: false
    trello-add-branch-category-label:
        description: Adds branch category (e.g. feature/foo) label to cards.
        default: true
    trello-conflicting-labels:
        description: |-
            List of label names separated by semicolon that should not coexist together (e.g. "feature;bug;chore"). If card has one and the PR has another one, then the PR label is ignored.
            Example:
            trello-conflicting-labels: |-
              feature;bug;chore
              foo;bar
    trello-card-position:
        description: Position of the card after being moved to a list. Can be "top" or "bottom".
        default: 'top'
    trello-add-members-to-cards:
        description: Adds PR author, contributors and assignees to the Trello card.
        default: true
    trello-switch-members-in-review:
        description: Replaces Trello card members with PR reviewers when PR is opened. It reassigns the PR author, contributors and assignees when the card is moved away from trello-list-id-pr-open.
        default: false
    trello-remove-unrelated-members:
        description: Removes card members who are not authors or assignees of the PR.
        default: true
    trello-archive-on-merge:
        description: Archives Trello cards when PR is merged.
        default: false
runs:
    using: node20
    main: 'dist/index.js'
